# Generated by Django 5.0.6 on 2024-07-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0003_book_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=255)),
                ('cemail', models.EmailField(max_length=255)),
                ('cphone', models.CharField(max_length=10)),
                ('cadd', models.CharField(max_length=255)),
                ('bname', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('totalamout', models.PositiveIntegerField()),
            ],
        ),
    ]
